CREATE ROLE pranav999 WITH LOGIN ENCRYPTED PASSWORD 'password';
CREATE DATABASE un_population OWNER pranav999;
CREATE DATABASE pranav999 OWNER pranav999;
/*
CREATE ROLE pranav WITH LOGIN ENCRYPTED PASSWORD 'password';
CREATE DATABASE un_population OWNER pranav;
*/
